//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.NewsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsService.ITopicalNewsService")]
    public interface ITopicalNewsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopicalNewsService/NewsFocus", ReplyAction="http://tempuri.org/ITopicalNewsService/NewsFocusResponse")]
        string[] NewsFocus(string[] keyWords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopicalNewsService/NewsFocus", ReplyAction="http://tempuri.org/ITopicalNewsService/NewsFocusResponse")]
        System.Threading.Tasks.Task<string[]> NewsFocusAsync(string[] keyWords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITopicalNewsServiceChannel : TryIt.NewsService.ITopicalNewsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TopicalNewsServiceClient : System.ServiceModel.ClientBase<TryIt.NewsService.ITopicalNewsService>, TryIt.NewsService.ITopicalNewsService {
        
        public TopicalNewsServiceClient() {
        }
        
        public TopicalNewsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TopicalNewsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopicalNewsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopicalNewsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] NewsFocus(string[] keyWords) {
            return base.Channel.NewsFocus(keyWords);
        }
        
        public System.Threading.Tasks.Task<string[]> NewsFocusAsync(string[] keyWords) {
            return base.Channel.NewsFocusAsync(keyWords);
        }
    }
}
